# Site wide configuration

title:            Software Critic
locale:           en_US
url:              https://irfanahmad.in


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# CSS Optimization

assets:
  compress:
    css: true
  js_compressor:  uglifier
  css_compressor: scss
  features:
    liquid: true

# Site owner
owner:
  name: Irfan Ahmad
  avatar: bio-photo.jpg
  bio: "Software Critic"
  linkedin: softwarescritic
  email: checkopser@gmail.com
  github: notimewaste
  disqus-shortname: irfanahmads
  twitter: notimewaste
  facebook: irfan.ahmad.7
  google:
    plus: #username
    analytics: UA-79191458-1
    verify:
    ad-client: #ca-pub-3196292578790862
    ad-slot:
  bing-verify:
  stackoverflow: 5257528/irfan-ahmad   #from a "http://stackoverflow.com/users/123456/username" link
  xing: #username
  instagram: software_critic
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: yes
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  calender: yes

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

collections:
  posts:
    output: true
  comics:
    output: true

defaults:
  - scope:
      path: "/posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "/comics"
      type: "comics"
    values:
      layout: post
